---
alias_groups:
  - name: General
    aliases:
      - name: ll
        command: ls -l
      - name: la
        command: ls -a
      - name: rc
        command: echo $?
      - name: arsync
        command: rsync -havuHP --stat
      - name: sl
        command: systemctl
      - name: jl
        command: journalctl
      - name: ip4
        command: ip -4 -br address
      - name: src
        command: source ${HOME%/}/.bashrc
  - name: Ansible
    aliases:
      - name: apb
        command: ansible-playbook
      - name: adoc
        command: ansible-doc
      - name: acfg
        command: ansible-config
      - name: avlt
        command: ansible-vault
      - name: agal
        command: ansible-galaxy
      - name: alint
        command: ansible-lint
  - name: Python
    aliases:
      - name: python
        command: python3
      - name: pypile
        command: python3 -m py_compile
      - name: pyvenv
        command: python3 -m venv
      
